### ISSUE TITLE
Little Insignifcant Things Compatibility

### ISSUE THREAD

**Issue by hextrace** [blay09/CraftingTweaks#100]
Not sure if it would be possible; however, I would like to put in a request to add in Little Insignificant Things (LIT) by M4THG33K.

**Comment by thephoenixlodge** [comment]
To go with this - Gemulation, which is a crossover addon between LIT and Silent's Gems

**Comment by BlayTheNinth** [comment]
Best way to get this done would be to ask their devs to register their crafting tables via the Crafting Tweaks IMC API (which is super simple to do and doesn't need a build dependency), because that's what I'd just end up PRing to them otherwise (and I have no idea when I'll have leftover time to spend doing that).

**Comment by BlayTheNinth** [comment]
Closing since LIT hasn't been updated past Minecraft 1.10.
