### ISSUE TITLE
Balancing the grid in a TiC crafting station causes u to crash

### ISSUE THREAD

**Issue by gefailter** [blay09/CraftingTweaks#104]
TiC version: 1.12-2.7.1.9
CT version: 1.12-8.1.1
Forge version: 2420

When u click the "balance grid" button in the crafting station u crash.

**Comment by BlayTheNinth** [comment]
The crash wasn't related to Crafting Tweaks, it was actually just a matter of the balance button overlapping with the recipe book button. Crafting Tweaks moves the recipe book button for vanilla crafting tables, but didn't yet for Tinkers Construct. The next version is going to move the button to the right of the GUI:
![CraftingStation](https://user-images.githubusercontent.com/1933180/28718872-1eb54802-73a8-11e7-9a7f-a382a17eaa14.png)
The crash on the recipe book remains of course, but is caused by another mod.
