### ISSUE TITLE
Crafting speed delay

### ISSUE THREAD

**Issue by ghost** [blay09/CraftingTweaks#121]
When shift click crafting a stack of items, the server often lags for a few seconds. Would it be possible to get an option to have a configurable "craft this many per second" option to spread out the computing load?

**Comment by BlayTheNinth** [comment]
I think an option like that would be better suited to one of the lag-solving mods, as Crafting Tweaks is meant to provide easier access to crafting without changing any actual crafting behaviour, and not focussed on enhancing the performance of the game or fixing vanilla bugs.

**Comment by ghost** [comment]
Even if another mod could come along and fix it, it would be better if the mod the problem is originating from could offer its own mitigation options.

**Comment by BlayTheNinth** [comment]
The problem is not originating from Crafting Tweaks, shift-clicking to craft a stack is a Vanilla feature that is known to cause lagspikes when used in a large pack in recent versions of Minecraft. There are mods around to fix it, such as [FastWorkbench](https://minecraft.curseforge.com/projects/fastworkbench).
