### ISSUE TITLE
crafting tweaks and fastworkbench conflict

### ISSUE THREAD

**Issue by Willy347** [blay09/CraftingTweaks#127]
when both these mods are installed:
CraftingTweaks_1.14.4-10.1.3
FastWorkbench-1.14.4-2.1.0 (Shadows_of_Fire)

the balance/spread button stops working but the keybinding does still work.

also reported to fastworkbench

**Comment by BlayTheNinth** [comment]
I assume this is due to FastWorkbench clearing the button list if `removeRecipeBook` is enabled.

https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.14/src/main/java/shadows/fastbench/gui/GuiFastBench.java#L18

Instead, it should only find and remove the recipe book button so that buttons added via the InitGui event remain in place.

https://github.com/Shadows-of-Fire/FastWorkbench/issues/27
