### ISSUE TITLE
[bug] "This server does not have crafting tweaks installed" even if both client and server has CT installed

### ISSUE THREAD

**Issue by tntblockman** [blay09/CraftingTweaks#71]
MC 1.7.10
Forge: 10.13.4.1614
Crafting Tweaks: 1.0.79

Hi,
I've got Crafting Tweaks both installed on client and server, but still receive message with ingame chat "This server does not have crafting tweaks installed" whilst joining server that has crafting Tweaks installed and successfully loaded(according to server console).  Could be the same issue as #65

**Comment by esotericist** [comment]
I'm also experiencing this on my server with a similar configuration (1.7.10, forge 1614, crafting tweaks 1.0.79). 

In #65, it's suggested that latency may be an issue, but in my case, I'm literally sitting next to the server; there's only a switch and a total of three feet of cat-6 between client and server and latency is sub 1 ms, so that can't be the issue.

Notably, it still _works_, it's just annoying to get an 'error' message every time we log in.

**Comment by phit** [comment]
Welp, looks like it's back for 1.9.4/1.10.2

craftingtweaks-mc1.9.4-5.0.6.jar
forge-12.18.1.2026

Would be lovely to see this fixed, thanks!

**Comment by slidingmike** [comment]
Can confirm, 5.0.6 and 2049 forge, same issue.

**Comment by BlayTheNinth** [comment]
Fixed in latest version.

**Comment by reallydrained** [comment]
I am having this issue =/

1.7.10, not even playing on server. I have CT installed.
